### ISSUE TITLE
Move to drupal.org

### ISSUE THREAD

**Issue by lukasfischer** [Lullabot/entity_browser_block_layout#1]
yip, would be great.

**Comment by lpeabody** [comment]
Bump on this. Chance of this making it up to Drupal.org in the near future?

**Comment by lkmorlan** [comment]
Work is underway here:
https://www.drupal.org/project/entity_browser_block/issues/3195862

**Comment by lkmorlan** [comment]
This is not moving ahead within entity_browser_block. Could you promote the sandbox project? Issue about this:
https://www.drupal.org/project/3023988/issues/3065860

**Comment by deviantintegral** [comment]
Looks like I don't have access to that. @karens can you followup?

Thanks all for moving this along!

**Comment by lkmorlan** [comment]
There is now a [drupal.org project](https://www.drupal.org/project/entity_browser_block_layout).

**Comment by deviantintegral** [comment]
Excellent! I've updated the readme and will archive this project in a moment.
